<?php

namespace App\Support;

class SiteDefaults
{
    public static function pages(): array
    {
        return [
            [
                'title' => 'Home',
                'slug' => 'home',
                'excerpt' => 'Websites, online stores, booking systems, and custom business tools built to help customers understand, trust, and choose your brand.',
                'seo_title' => 'Bakhtech Solutions | Websites, Online Stores & Business Tools',
                'seo_description' => 'Bakhtech Solutions builds modern websites, ecommerce stores, booking systems, and custom web apps for businesses that want a stronger online presence.',
                'focus_keyword' => 'business website development',
            ],
            [
                'title' => 'About',
                'slug' => 'about',
                'excerpt' => 'Meet the team helping businesses turn ideas into clear, reliable websites, shops, booking flows, and digital systems.',
                'seo_title' => 'About Bakhtech Solutions | Practical Web Design & Development',
                'seo_description' => 'Learn how Bakhtech Solutions helps businesses plan, design, and launch websites and digital tools that are easy to use and built for growth.',
                'focus_keyword' => 'web design and development',
            ],
            [
                'title' => 'Portfolio',
                'slug' => 'portfolio',
                'excerpt' => 'Explore real websites, ecommerce stores, booking platforms, dashboards, and custom web apps built for business goals.',
                'seo_title' => 'Bakhtech Solutions Portfolio | Websites, Stores & Web Apps',
                'seo_description' => 'View selected Bakhtech Solutions projects, including business websites, ecommerce stores, booking platforms, dashboards, and custom web apps.',
                'focus_keyword' => 'website portfolio',
            ],
            [
                'title' => 'Ebook',
                'slug' => 'ebook',
                'excerpt' => 'Plain-English website planning resources for business owners who want a clearer, stronger online presence.',
                'seo_title' => 'Website Strategy Ebook | Bakhtech Solutions',
                'seo_description' => 'Download practical website planning resources from Bakhtech Solutions for improving your online presence, customer journey, and digital systems.',
                'focus_keyword' => 'website strategy ebook',
            ],
            [
                'title' => 'Career',
                'slug' => 'career',
                'excerpt' => 'Work with Bakhtech Solutions on practical websites, ecommerce projects, booking systems, and business automation tools.',
                'seo_title' => 'Careers | Bakhtech Solutions',
                'seo_description' => 'Explore career opportunities with Bakhtech Solutions across web design, frontend development, Laravel, content, and digital product work.',
                'focus_keyword' => 'web development careers',
            ],
            [
                'title' => 'Contact',
                'slug' => 'contact',
                'excerpt' => 'Tell us what you want to build, improve, or automate, and we will help you choose the right next step.',
                'seo_title' => 'Contact Bakhtech Solutions | Start Your Website or Web App',
                'seo_description' => 'Contact Bakhtech Solutions to plan a website, ecommerce store, booking system, dashboard, client portal, or custom web application.',
                'focus_keyword' => 'start website project',
            ],
        ];
    }

    public static function settings(): array
    {
        return [
            'siteName' => 'Bakhtech Solutions',
            'contactEmail' => 'solutions@bakhtech.com.ng',
            'phone' => '+234 708 637 2833',
            'activeHome' => 'home',
            'homePortfolioShowDescriptions' => 'true',
            'homepageVideoUrl' => '',
            'theme_light_primary' => '#1261ff',
            'theme_light_secondary' => '#12c8a0',
            'theme_light_active' => '#ef4444',
            'theme_dark_primary' => '#8bb8ff',
            'theme_dark_secondary' => '#67e8cf',
            'theme_dark_active' => '#ef4444',
            'navigation_items' => json_encode([
                ['label' => 'Home', 'href' => '/', 'visible' => true],
                ['label' => 'About', 'href' => '/about', 'visible' => true],
                ['label' => 'Portfolio', 'href' => '/portfolio', 'visible' => true, 'children' => []],
                ['label' => 'Booking', 'href' => '/booking', 'visible' => true],
                ['label' => 'Contact', 'href' => '/contact', 'visible' => true],
            ]),
            'googleReviewUrl' => '',
            'google_business_client_id' => '',
            'google_business_client_secret' => '',
            'trustpilotReviewUrl' => '',
            'reviewFrontendMinWords' => '0',
            'reviewFrontendMaxWords' => '0',
            'reviewFrontendMinCharacters' => '0',
            'reviewFrontendMaxCharacters' => '0',
            'reviewFrontendMinRating' => '1',
            'reviewFrontendProvider' => 'all',
            'reviewFrontendFeaturedOnly' => 'false',
            'reviewFrontendLimit' => '6',
            'facebookUrl' => '',
            'instagramUrl' => '',
            'linkedinUrl' => '',
            'tiktokUrl' => '',
            'twitterUrl' => '',
            'youtubeUrl' => '',
            'bookingIntro' => 'Choose a service, pick an available time, and receive a calendar invitation with reminders.',
            'invoicePaymentEnabled' => 'true',
            'invoiceDefaultPaymentGateway' => 'paystack',
            'invoiceEnabledPaymentGateways' => 'paystack,flutterwave',
            'company_name' => 'Bakhtech Solutions',
            'company_logo' => '/bakhtech-logo-light.png',
            'company_email' => 'solutions@bakhtech.com.ng',
            'company_phone' => '+234 708 637 2833',
            'company_address' => '',
            'company_website' => 'https://bakhtech.com.ng',
            'quote_prefix' => 'QT-',
            'invoice_prefix' => 'INV-',
            'starting_number' => '1000',
            'receipt_starting_number' => '1000',
            'currency' => 'NGN',
            'currency_symbol' => '',
            'pricing_rate_usd' => '0.00067',
            'pricing_rate_gbp' => '0.00053',
            'default_tax_rate' => '7.5',
            'tax_label' => 'VAT',
            'homepage_url' => '/',
            'homepage_label' => 'Homepage',
            'gateway_active' => 'paystack',
            'gateway_mode' => 'test',
            'enable_partial_payments' => '1',
            'paystack_public_test' => '',
            'paystack_secret_test' => '',
            'paystack_public_live' => '',
            'paystack_secret_live' => '',
            'flutter_public_test' => '',
            'flutter_secret_test' => '',
            'flutter_public_live' => '',
            'flutter_secret_live' => '',
            'bank_account_name' => '',
            'bank_account_number' => '',
            'bank_bank_name' => '',
            'bank_instructions' => '',
            'bank_currency_accounts' => '[]',
        ];
    }
}
