<?php

namespace App\Support;

class SiteDefaults
{
    public static function pages(): array
    {
        return [
            [
                'title' => 'Home',
                'slug' => 'home',
                'excerpt' => 'Fast, SEO-ready websites, ecommerce stores, booking systems, and custom web apps for businesses in Nigeria, the United States, Canada, and worldwide.',
                'seo_title' => 'Bakhtech Solutions | SEO Web Design & Web Apps',
                'seo_description' => 'Bakhtech Solutions builds fast, SEO-ready websites, ecommerce stores, booking systems and custom web apps for businesses in Nigeria, the US, Canada and worldwide.',
                'focus_keyword' => 'SEO web design agency',
            ],
            [
                'title' => 'About',
                'slug' => 'about',
                'excerpt' => 'Learn how Bakhtech Solutions designs and develops conversion-focused websites and web systems for growing businesses.',
                'seo_title' => 'About Bakhtech Solutions | Web Design Agency',
                'seo_description' => 'Meet Bakhtech Solutions, a web design and development agency building fast websites, ecommerce stores, booking systems and business web apps.',
                'focus_keyword' => 'web design agency',
            ],
            [
                'title' => 'Portfolio',
                'slug' => 'portfolio',
                'excerpt' => 'Explore Bakhtech Solutions web design, ecommerce, booking system, and custom web app projects.',
                'seo_title' => 'Web Design Portfolio | Bakhtech Solutions',
                'seo_description' => 'See websites, ecommerce stores, booking platforms and custom web apps built by Bakhtech Solutions for real businesses.',
                'focus_keyword' => 'web design portfolio',
            ],
            [
                'title' => 'Ebook',
                'slug' => 'ebook',
                'excerpt' => 'Practical website strategy resources for business owners planning a stronger online presence.',
                'seo_title' => 'Website Strategy Ebook | Bakhtech Solutions',
                'seo_description' => 'Download practical website strategy resources from Bakhtech Solutions for planning SEO-ready business websites and digital systems.',
                'focus_keyword' => 'website strategy ebook',
            ],
            [
                'title' => 'Career',
                'slug' => 'career',
                'excerpt' => 'Work with Bakhtech Solutions on modern web design, development, SEO, ecommerce, and business automation projects.',
                'seo_title' => 'Careers | Bakhtech Solutions',
                'seo_description' => 'Explore career opportunities with Bakhtech Solutions across web design, frontend development, Laravel, SEO and digital product work.',
                'focus_keyword' => 'web design careers',
            ],
            [
                'title' => 'Contact',
                'slug' => 'contact',
                'excerpt' => 'Talk to Bakhtech Solutions about your website, ecommerce store, booking system, portal, dashboard, or SEO project.',
                'seo_title' => 'Contact Bakhtech Solutions | Start Your Website Project',
                'seo_description' => 'Contact Bakhtech Solutions to plan a fast, SEO-ready website, ecommerce store, booking system, dashboard, or custom web app.',
                'focus_keyword' => 'contact web design agency',
            ],
        ];
    }

    public static function settings(): array
    {
        return [
            'siteName' => 'Bakhtech Solutions',
            'contactEmail' => 'solutions@bakhtech.com.ng',
            'phone' => '+234 708 637 2833',
            'activeHome' => 'home',
            'homePortfolioShowDescriptions' => 'true',
            'homepageVideoUrl' => '',
            'theme_light_primary' => '#1261ff',
            'theme_light_secondary' => '#12c8a0',
            'theme_light_active' => '#ef4444',
            'theme_dark_primary' => '#8bb8ff',
            'theme_dark_secondary' => '#67e8cf',
            'theme_dark_active' => '#ef4444',
            'navigation_items' => json_encode([
                ['label' => 'Home', 'href' => '/', 'visible' => true],
                ['label' => 'About', 'href' => '/about', 'visible' => true],
                ['label' => 'Portfolio', 'href' => '/portfolio', 'visible' => true, 'children' => []],
                ['label' => 'Booking', 'href' => '/booking', 'visible' => true],
                ['label' => 'Contact', 'href' => '/contact', 'visible' => true],
            ]),
            'googleReviewUrl' => '',
            'google_business_client_id' => '',
            'google_business_client_secret' => '',
            'trustpilotReviewUrl' => '',
            'reviewFrontendMinWords' => '0',
            'reviewFrontendMaxWords' => '0',
            'reviewFrontendMinCharacters' => '0',
            'reviewFrontendMaxCharacters' => '0',
            'reviewFrontendMinRating' => '1',
            'reviewFrontendProvider' => 'all',
            'reviewFrontendFeaturedOnly' => 'false',
            'reviewFrontendLimit' => '6',
            'facebookUrl' => '',
            'instagramUrl' => '',
            'linkedinUrl' => '',
            'tiktokUrl' => '',
            'twitterUrl' => '',
            'youtubeUrl' => '',
            'bookingIntro' => 'Choose a service, pick an available time, and receive a calendar invitation with reminders.',
            'invoicePaymentEnabled' => 'true',
            'invoiceDefaultPaymentGateway' => 'paystack',
            'invoiceEnabledPaymentGateways' => 'paystack,flutterwave',
            'company_name' => 'Bakhtech Solutions',
            'company_logo' => '/bakhtech-logo-light.png',
            'company_email' => 'solutions@bakhtech.com.ng',
            'company_phone' => '+234 708 637 2833',
            'company_address' => '',
            'company_website' => 'https://bakhtech.com.ng',
            'quote_prefix' => 'QT-',
            'invoice_prefix' => 'INV-',
            'starting_number' => '1000',
            'receipt_starting_number' => '1000',
            'currency' => 'NGN',
            'currency_symbol' => '',
            'pricing_rate_usd' => '0.00067',
            'pricing_rate_gbp' => '0.00053',
            'default_tax_rate' => '7.5',
            'tax_label' => 'VAT',
            'homepage_url' => '/',
            'homepage_label' => 'Homepage',
            'gateway_active' => 'paystack',
            'gateway_mode' => 'test',
            'enable_partial_payments' => '1',
            'paystack_public_test' => '',
            'paystack_secret_test' => '',
            'paystack_public_live' => '',
            'paystack_secret_live' => '',
            'flutter_public_test' => '',
            'flutter_secret_test' => '',
            'flutter_public_live' => '',
            'flutter_secret_live' => '',
            'bank_account_name' => '',
            'bank_account_number' => '',
            'bank_bank_name' => '',
            'bank_instructions' => '',
            'bank_currency_accounts' => '[]',
        ];
    }
}
